### ISSUE TITLE
CSS styles not loaded

### ISSUE THREAD

**Issue by binair-io** [markhermano/paperizer#10]
Sometimes the CSS styles are not loaded prior to the print window appearing. It doesn't happen every time. Occurs both when using local relative path as well as direct link (http)

<pre>const { paperize } = usePaperizer('datatable', {
    styles: [
        '/src/styles/print-planning.css'
    ]
})</pre>

**Comment by markhermano** [comment]
@binair-io you'll have to place your local CSS in the public folder. See here: https://github.com/markhermano/paperizer/issues/8#issuecomment-1652746638

**Comment by binair-io** [comment]
Indeed, that worked. Thanks!
