### ISSUE TITLE
How to use a local css file for styles

### ISSUE THREAD

**Issue by manastalukdar** [markhermano/paperizer#8]
```
const { paperize } = usePaperizer('printMe',  {
  styles: [
  //'https://cdn.jsdelivr.net/npm/bootstrap@latest/dist/css/bootstrap.min.css', <- works
    '../../style/print-custom.css' <- does not work
  ]
});
```

Using the local file as shown above does not seem to take affect.

**Comment by marioflotae81** [comment]
I have the same issue, did you figure out how to do it?

**Comment by manastalukdar** [comment]
It works if you copy-paste the entire css as a string as part of the styles array. Interestingly that worked only in production and not in development mode. I would still like to know how to make it work using a local css file.

**Comment by markhermano** [comment]
Hi guys, 

The only way to make this work is to place your CSS files inside the public folder.

Assuming your CSS file is in the root of the public folder, you can do:
```js
const { paperize } = usePaperizer('printMe',  {
  styles: [
    '/print-custom.css'
  ]
});
```

Let me know if this works for you.

**Comment by manastalukdar** [comment]
Thanks @markhermano . That works.
