### ISSUE TITLE
Using Paperizer with dynamic components

### ISSUE THREAD

**Issue by jaywilburn** [markhermano/paperizer#9]
Is there a way to use this to print out a child component using this?
` <Component>
                <component
                  :is="selectedTemp.component"
                  :data="data"
                />
              </Component>`

It prints out the data props but not the actual component.

**Comment by markhermano** [comment]
@jaywilburn 
So it prints the data props, which means it's working. The problem might be in the CSS which does not display the component correctly in the print preview.

**Comment by jaywilburn** [comment]
Hmm, maybe it's a vite issue. It's a very simple Vue app with tailwind, so it might be something there. I'll try there and see what I find. Thanks!
